//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Game2048.Maui.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Game2048.Maui.Resources.Localization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Deep ocean drive. Get ready for the dive!.
        /// </summary>
        public static string AbyssTheme_desc {
            get {
                return ResourceManager.GetString("AbyssTheme_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Abyss.
        /// </summary>
        public static string AbyssTheme_title {
            get {
                return ResourceManager.GetString("AbyssTheme_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unlocked all achievements in the game.
        /// </summary>
        public static string Ach_AllAchievementsUnlocked_desc {
            get {
                return ResourceManager.GetString("Ach_AllAchievementsUnlocked_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Platinum.
        /// </summary>
        public static string Ach_AllAchievementsUnlocked_title {
            get {
                return ResourceManager.GetString("Ach_AllAchievementsUnlocked_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unlocked all themes in the game.
        /// </summary>
        public static string Ach_AllThemesUnlocked_desc {
            get {
                return ResourceManager.GetString("Ach_AllThemesUnlocked_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Should have been microtransactions.
        /// </summary>
        public static string Ach_AllThemesUnlocked_title {
            get {
                return ResourceManager.GetString("Ach_AllThemesUnlocked_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Earned 1000 coins for the whole time.
        /// </summary>
        public static string Ach_Earn1000Coins_desc {
            get {
                return ResourceManager.GetString("Ach_Earn1000Coins_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bankroll.
        /// </summary>
        public static string Ach_Earn1000Coins_title {
            get {
                return ResourceManager.GetString("Ach_Earn1000Coins_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Earned 2000 coins for the whole time.
        /// </summary>
        public static string Ach_Earn2000Coins_desc {
            get {
                return ResourceManager.GetString("Ach_Earn2000Coins_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Money maker.
        /// </summary>
        public static string Ach_Earn2000Coins_title {
            get {
                return ResourceManager.GetString("Ach_Earn2000Coins_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Earned 5000 coins for the whole time.
        /// </summary>
        public static string Ach_Earn5000Coins_title {
            get {
                return ResourceManager.GetString("Ach_Earn5000Coins_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Played your first game in 2048.
        /// </summary>
        public static string Ach_FirstGame_desc {
            get {
                return ResourceManager.GetString("Ach_FirstGame_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на First steps.
        /// </summary>
        public static string Ach_FirstGame_title {
            get {
                return ResourceManager.GetString("Ach_FirstGame_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Used undo for the first time.
        /// </summary>
        public static string Ach_FirstUndo_desc {
            get {
                return ResourceManager.GetString("Ach_FirstUndo_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Forward to the past!.
        /// </summary>
        public static string Ach_FirstUndo_title {
            get {
                return ResourceManager.GetString("Ach_FirstUndo_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Won for the first time.
        /// </summary>
        public static string Ach_FirstWin_desc {
            get {
                return ResourceManager.GetString("Ach_FirstWin_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sweet victory.
        /// </summary>
        public static string Ach_FirstWin_title {
            get {
                return ResourceManager.GetString("Ach_FirstWin_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Made 1000 moves.
        /// </summary>
        public static string Ach_Move1000_desc {
            get {
                return ResourceManager.GetString("Ach_Move1000_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Watch my moves.
        /// </summary>
        public static string Ach_Move1000_title {
            get {
                return ResourceManager.GetString("Ach_Move1000_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Beaten 2048 without undo .
        /// </summary>
        public static string Ach_NoUndoVictory_desc {
            get {
                return ResourceManager.GetString("Ach_NoUndoVictory_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No mistakes!.
        /// </summary>
        public static string Ach_NoUndoVictory_title {
            get {
                return ResourceManager.GetString("Ach_NoUndoVictory_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Played 100 games.
        /// </summary>
        public static string Ach_Play100Games_desc {
            get {
                return ResourceManager.GetString("Ach_Play100Games_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Gamer.
        /// </summary>
        public static string Ach_Play100Games_title {
            get {
                return ResourceManager.GetString("Ach_Play100Games_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Played 10 games.
        /// </summary>
        public static string Ach_Play10Games_desc {
            get {
                return ResourceManager.GetString("Ach_Play10Games_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Keep trying.
        /// </summary>
        public static string Ach_Play10Games_title {
            get {
                return ResourceManager.GetString("Ach_Play10Games_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Merged a 1024 tile.
        /// </summary>
        public static string Ach_Reach1024_desc {
            get {
                return ResourceManager.GetString("Ach_Reach1024_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Almost there!.
        /// </summary>
        public static string Ach_Reach1024_title {
            get {
                return ResourceManager.GetString("Ach_Reach1024_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Merged a 128 tile.
        /// </summary>
        public static string Ach_Reach128_desc {
            get {
                return ResourceManager.GetString("Ach_Reach128_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Wasn&apos;t that hard, right?.
        /// </summary>
        public static string Ach_Reach128_title {
            get {
                return ResourceManager.GetString("Ach_Reach128_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Merged a 2048 tile.
        /// </summary>
        public static string Ach_Reach2048_desc {
            get {
                return ResourceManager.GetString("Ach_Reach2048_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на GOLD GOLD GOLD.
        /// </summary>
        public static string Ach_Reach2048_title {
            get {
                return ResourceManager.GetString("Ach_Reach2048_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Merged a 256 tile.
        /// </summary>
        public static string Ach_Reach256_desc {
            get {
                return ResourceManager.GetString("Ach_Reach256_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 2^8.
        /// </summary>
        public static string Ach_Reach256_title {
            get {
                return ResourceManager.GetString("Ach_Reach256_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Merged a 4096 tile... Lord have mercy....
        /// </summary>
        public static string Ach_Reach4096_desc {
            get {
                return ResourceManager.GetString("Ach_Reach4096_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на How did you do it?.
        /// </summary>
        public static string Ach_Reach4096_title {
            get {
                return ResourceManager.GetString("Ach_Reach4096_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Merged a 512 tile.
        /// </summary>
        public static string Ach_Reach512_desc {
            get {
                return ResourceManager.GetString("Ach_Reach512_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Two more to go!.
        /// </summary>
        public static string Ach_Reach512_title {
            get {
                return ResourceManager.GetString("Ach_Reach512_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Merged a 64 tile.
        /// </summary>
        public static string Ach_Reach64_desc {
            get {
                return ResourceManager.GetString("Ach_Reach64_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на That&apos;s going somewhere!.
        /// </summary>
        public static string Ach_Reach64_title {
            get {
                return ResourceManager.GetString("Ach_Reach64_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Scored 1000 points in one game.
        /// </summary>
        public static string Ach_Score1000_desc {
            get {
                return ResourceManager.GetString("Ach_Score1000_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Scorer.
        /// </summary>
        public static string Ach_Score1000_title {
            get {
                return ResourceManager.GetString("Ach_Score1000_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Scored 10000 points in one game.
        /// </summary>
        public static string Ach_Score10000_desc {
            get {
                return ResourceManager.GetString("Ach_Score10000_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на How many tiles does it take?.
        /// </summary>
        public static string Ach_Score10000_title {
            get {
                return ResourceManager.GetString("Ach_Score10000_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Scored 20000 points in one game.
        /// </summary>
        public static string Ach_Score20000_desc {
            get {
                return ResourceManager.GetString("Ach_Score20000_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Okay, that&apos;s a big one.
        /// </summary>
        public static string Ach_Score20000_title {
            get {
                return ResourceManager.GetString("Ach_Score20000_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Scored 30000 points in one game.
        /// </summary>
        public static string Ach_Score30000_desc {
            get {
                return ResourceManager.GetString("Ach_Score30000_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Big boy scorer.
        /// </summary>
        public static string Ach_Score30000_title {
            get {
                return ResourceManager.GetString("Ach_Score30000_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Scored 45000 points in one game.
        /// </summary>
        public static string Ach_Score45000_desc {
            get {
                return ResourceManager.GetString("Ach_Score45000_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на To infinity and beyond.
        /// </summary>
        public static string Ach_Score45000_title {
            get {
                return ResourceManager.GetString("Ach_Score45000_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Scored 5000 points in one game.
        /// </summary>
        public static string Ach_Score5000_desc {
            get {
                return ResourceManager.GetString("Ach_Score5000_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Big numbers.
        /// </summary>
        public static string Ach_Score5000_title {
            get {
                return ResourceManager.GetString("Ach_Score5000_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ???.
        /// </summary>
        public static string Ach_Why30_desc {
            get {
                return ResourceManager.GetString("Ach_Why30_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на What did you expect?.
        /// </summary>
        public static string Ach_Why30_title {
            get {
                return ResourceManager.GetString("Ach_Why30_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Won 10 times.
        /// </summary>
        public static string Ach_Win10Times_desc {
            get {
                return ResourceManager.GetString("Ach_Win10Times_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Like first time.
        /// </summary>
        public static string Ach_Win10Times_title {
            get {
                return ResourceManager.GetString("Ach_Win10Times_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Won 25 times.
        /// </summary>
        public static string Ach_Win25Times_desc {
            get {
                return ResourceManager.GetString("Ach_Win25Times_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Absolute champion.
        /// </summary>
        public static string Ach_Win25Times_title {
            get {
                return ResourceManager.GetString("Ach_Win25Times_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Won 3 times.
        /// </summary>
        public static string Ach_Win3Times_desc {
            get {
                return ResourceManager.GetString("Ach_Win3Times_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Triple shot.
        /// </summary>
        public static string Ach_Win3Times_title {
            get {
                return ResourceManager.GetString("Ach_Win3Times_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Won 5 times.
        /// </summary>
        public static string Ach_Win5Times_desc {
            get {
                return ResourceManager.GetString("Ach_Win5Times_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ace.
        /// </summary>
        public static string Ach_Win5Times_title {
            get {
                return ResourceManager.GetString("Ach_Win5Times_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reached a final tile in Chill Zone mode.
        /// </summary>
        public static string Ach_WinChillZoneMode_desc {
            get {
                return ResourceManager.GetString("Ach_WinChillZoneMode_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Proud amateur.
        /// </summary>
        public static string Ach_WinChillZoneMode_title {
            get {
                return ResourceManager.GetString("Ach_WinChillZoneMode_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reached a final tile in Classic mode.
        /// </summary>
        public static string Ach_WinClassicMode_desc {
            get {
                return ResourceManager.GetString("Ach_WinClassicMode_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на True purist.
        /// </summary>
        public static string Ach_WinClassicMode_title {
            get {
                return ResourceManager.GetString("Ach_WinClassicMode_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reached a final tile in Classic Plus mode.
        /// </summary>
        public static string Ach_WinClassicPlusMode_desc {
            get {
                return ResourceManager.GetString("Ach_WinClassicPlusMode_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Innovations are not bad.
        /// </summary>
        public static string Ach_WinClassicPlusMode_title {
            get {
                return ResourceManager.GetString("Ach_WinClassicPlusMode_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reached a final tile in Compact mode.
        /// </summary>
        public static string Ach_WinCompactMode_desc {
            get {
                return ResourceManager.GetString("Ach_WinCompactMode_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Claustrophobia.
        /// </summary>
        public static string Ach_WinCompactMode_title {
            get {
                return ResourceManager.GetString("Ach_WinCompactMode_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reached a final tile in Extended mode.
        /// </summary>
        public static string Ach_WinExtendedMode_desc {
            get {
                return ResourceManager.GetString("Ach_WinExtendedMode_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hardcore lover.
        /// </summary>
        public static string Ach_WinExtendedMode_title {
            get {
                return ResourceManager.GetString("Ach_WinExtendedMode_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Progress.
        /// </summary>
        public static string Achievements_progress_label {
            get {
                return ResourceManager.GetString("Achievements_progress_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Achievements.
        /// </summary>
        public static string Achievements_title {
            get {
                return ResourceManager.GetString("Achievements_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tonight&apos;s the night....
        /// </summary>
        public static string BayHarbourTheme_desc {
            get {
                return ResourceManager.GetString("BayHarbourTheme_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bay Harbour.
        /// </summary>
        public static string BayHarbourTheme_title {
            get {
                return ResourceManager.GetString("BayHarbourTheme_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Two colors, nothing else.
        /// </summary>
        public static string BWTheme_desc {
            get {
                return ResourceManager.GetString("BWTheme_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Black &amp; White.
        /// </summary>
        public static string BWTheme_title {
            get {
                return ResourceManager.GetString("BWTheme_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Classic 2048 theme.
        /// </summary>
        public static string ClassicTheme_desc {
            get {
                return ResourceManager.GetString("ClassicTheme_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Classic theme.
        /// </summary>
        public static string ClassicTheme_title {
            get {
                return ResourceManager.GetString("ClassicTheme_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Confirm.
        /// </summary>
        public static string ConfirmationOverlay_confirm_btn_text {
            get {
                return ResourceManager.GetString("ConfirmationOverlay_confirm_btn_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Restart is needed to change the language. Please confirm restart..
        /// </summary>
        public static string ConfirmationOverlay_desc {
            get {
                return ResourceManager.GetString("ConfirmationOverlay_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Confirmation.
        /// </summary>
        public static string ConfirmationOverlay_title {
            get {
                return ResourceManager.GetString("ConfirmationOverlay_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Wake up, samurai, we have a tile to achieve....
        /// </summary>
        public static string Cyberpunk2078Theme_desc {
            get {
                return ResourceManager.GetString("Cyberpunk2078Theme_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cyberpunk 2078.
        /// </summary>
        public static string Cyberpunk2078Theme_title {
            get {
                return ResourceManager.GetString("Cyberpunk2078Theme_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Classic dark 2048 theme.
        /// </summary>
        public static string DarkTheme_desc {
            get {
                return ResourceManager.GetString("DarkTheme_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Dark theme.
        /// </summary>
        public static string DarkTheme_title {
            get {
                return ResourceManager.GetString("DarkTheme_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cover the tile with emerald. Feel the luxury.
        /// </summary>
        public static string EmeraldBloomNumberlessTheme_desc {
            get {
                return ResourceManager.GetString("EmeraldBloomNumberlessTheme_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Emerald bloom (Numberless).
        /// </summary>
        public static string EmeraldBloomNumberlessTheme_title {
            get {
                return ResourceManager.GetString("EmeraldBloomNumberlessTheme_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Best.
        /// </summary>
        public static string Game_ScoreBoard_best_score_label {
            get {
                return ResourceManager.GetString("Game_ScoreBoard_best_score_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Score.
        /// </summary>
        public static string Game_ScoreBoard_score_label {
            get {
                return ResourceManager.GetString("Game_ScoreBoard_score_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings.
        /// </summary>
        public static string Game_settings_btn_text {
            get {
                return ResourceManager.GetString("Game_settings_btn_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 2048.
        /// </summary>
        public static string Game_title {
            get {
                return ResourceManager.GetString("Game_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Undo.
        /// </summary>
        public static string Game_undo_btn_text {
            get {
                return ResourceManager.GetString("Game_undo_btn_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Extended 5x5 mode with undo ability.
        /// </summary>
        public static string GameMode_ChillZone_desc {
            get {
                return ResourceManager.GetString("GameMode_ChillZone_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Chill Zone.
        /// </summary>
        public static string GameMode_ChillZone_title {
            get {
                return ResourceManager.GetString("GameMode_ChillZone_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 4x4.
        /// </summary>
        public static string GameMode_Classic_desc {
            get {
                return ResourceManager.GetString("GameMode_Classic_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Classic 2048.
        /// </summary>
        public static string GameMode_Classic_title {
            get {
                return ResourceManager.GetString("GameMode_Classic_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 4x4 + Undo.
        /// </summary>
        public static string GameMode_ClassicPlus_desc {
            get {
                return ResourceManager.GetString("GameMode_ClassicPlus_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Classic+.
        /// </summary>
        public static string GameMode_ClassicPlus_title {
            get {
                return ResourceManager.GetString("GameMode_ClassicPlus_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 3x3 + Undo (tile to win - 1024).
        /// </summary>
        public static string GameMode_Compact_desc {
            get {
                return ResourceManager.GetString("GameMode_Compact_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Compact.
        /// </summary>
        public static string GameMode_Compact_title {
            get {
                return ResourceManager.GetString("GameMode_Compact_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 5x5 hardcore mode with doubled spawn.
        /// </summary>
        public static string GameMode_Extended_desc {
            get {
                return ResourceManager.GetString("GameMode_Extended_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Extended 2048.
        /// </summary>
        public static string GameMode_Extended_title {
            get {
                return ResourceManager.GetString("GameMode_Extended_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MODE SELECTION.
        /// </summary>
        public static string GameModes_title {
            get {
                return ResourceManager.GetString("GameModes_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Menu.
        /// </summary>
        public static string GameOverOverlay_menu_btn_text {
            get {
                return ResourceManager.GetString("GameOverOverlay_menu_btn_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Try again.
        /// </summary>
        public static string GameOverOverlay_restart_btn_text {
            get {
                return ResourceManager.GetString("GameOverOverlay_restart_btn_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на GAME OVER.
        /// </summary>
        public static string GameOverOverlay_title {
            get {
                return ResourceManager.GetString("GameOverOverlay_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Undo 5 moves.
        /// </summary>
        public static string GameOverOverlay_undo5_btn_text {
            get {
                return ResourceManager.GetString("GameOverOverlay_undo5_btn_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Toxic yellow and lime theme. Careful!.
        /// </summary>
        public static string HazardTheme_desc {
            get {
                return ResourceManager.GetString("HazardTheme_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hazard.
        /// </summary>
        public static string HazardTheme_title {
            get {
                return ResourceManager.GetString("HazardTheme_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Swipe to move the tiles on a board.
        /// </summary>
        public static string HowToCard_1_desc {
            get {
                return ResourceManager.GetString("HowToCard_1_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Move tiles.
        /// </summary>
        public static string HowToCard_1_title {
            get {
                return ResourceManager.GetString("HowToCard_1_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tiles with the same value will merge in their sum.
        /// </summary>
        public static string HowToCard_2_desc {
            get {
                return ResourceManager.GetString("HowToCard_2_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Merge tiles.
        /// </summary>
        public static string HowToCard_2_title {
            get {
                return ResourceManager.GetString("HowToCard_2_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на If you are out of possible moves - you lose.
        /// </summary>
        public static string HowToCard_3_desc {
            get {
                return ResourceManager.GetString("HowToCard_3_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Try to always merge.
        /// </summary>
        public static string HowToCard_3_title {
            get {
                return ResourceManager.GetString("HowToCard_3_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You can undo a couple of moves to prevent your loss in some game modes.
        /// </summary>
        public static string HowToCard_4_desc {
            get {
                return ResourceManager.GetString("HowToCard_4_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Undo moves.
        /// </summary>
        public static string HowToCard_4_title {
            get {
                return ResourceManager.GetString("HowToCard_4_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unlock achievements, improve your statistics and earn coins.
        /// </summary>
        public static string HowToCard_5_desc {
            get {
                return ResourceManager.GetString("HowToCard_5_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Collect achievements.
        /// </summary>
        public static string HowToCard_5_title {
            get {
                return ResourceManager.GetString("HowToCard_5_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Spend your coins on new themes and make your own gaming experience .
        /// </summary>
        public static string HowToCard_6_desc {
            get {
                return ResourceManager.GetString("HowToCard_6_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Get stylish.
        /// </summary>
        public static string HowToCard_6_title {
            get {
                return ResourceManager.GetString("HowToCard_6_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на How to play.
        /// </summary>
        public static string HowToPage_title {
            get {
                return ResourceManager.GetString("HowToPage_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Drink to warm up your heart.
        /// </summary>
        public static string MatchaCreamTheme_desc {
            get {
                return ResourceManager.GetString("MatchaCreamTheme_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Matcha cream.
        /// </summary>
        public static string MatchaCreamTheme_title {
            get {
                return ResourceManager.GetString("MatchaCreamTheme_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на GAME MODES.
        /// </summary>
        public static string Menu_game_modes_btn_text {
            get {
                return ResourceManager.GetString("Menu_game_modes_btn_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на HOW TO.
        /// </summary>
        public static string Menu_how_to_btn_text {
            get {
                return ResourceManager.GetString("Menu_how_to_btn_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SETTINGS.
        /// </summary>
        public static string Menu_settings_btn_text {
            get {
                return ResourceManager.GetString("Menu_settings_btn_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ver. 1.0.
        /// </summary>
        public static string Menu_version_text {
            get {
                return ResourceManager.GetString("Menu_version_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на From white to black, let it happen.
        /// </summary>
        public static string MonochromeNumberlessTheme_desc {
            get {
                return ResourceManager.GetString("MonochromeNumberlessTheme_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Monochrome (Numberless).
        /// </summary>
        public static string MonochromeNumberlessTheme_title {
            get {
                return ResourceManager.GetString("MonochromeNumberlessTheme_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Green and blue based nature theme.
        /// </summary>
        public static string NatureTheme_desc {
            get {
                return ResourceManager.GetString("NatureTheme_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Nature.
        /// </summary>
        public static string NatureTheme_title {
            get {
                return ResourceManager.GetString("NatureTheme_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Astronomically cool theme....
        /// </summary>
        public static string NebulaTheme_desc {
            get {
                return ResourceManager.GetString("NebulaTheme_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Nebula.
        /// </summary>
        public static string NebulaTheme_title {
            get {
                return ResourceManager.GetString("NebulaTheme_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bright colors and dark background.
        /// </summary>
        public static string NeonColorTheme_desc {
            get {
                return ResourceManager.GetString("NeonColorTheme_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Neon.
        /// </summary>
        public static string NeonColorTheme_title {
            get {
                return ResourceManager.GetString("NeonColorTheme_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 21 shades of pink.
        /// </summary>
        public static string PinkyPinkTheme_desc {
            get {
                return ResourceManager.GetString("PinkyPinkTheme_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Man&apos;s choise.
        /// </summary>
        public static string PinkyPinkTheme_title {
            get {
                return ResourceManager.GetString("PinkyPinkTheme_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Achievements unlocked.
        /// </summary>
        public static string ProfilePage_achievements_unlocked_label {
            get {
                return ResourceManager.GetString("ProfilePage_achievements_unlocked_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Average score.
        /// </summary>
        public static string ProfilePage_average_score_label {
            get {
                return ResourceManager.GetString("ProfilePage_average_score_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Best mode.
        /// </summary>
        public static string ProfilePage_best_mode_label {
            get {
                return ResourceManager.GetString("ProfilePage_best_mode_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Games played.
        /// </summary>
        public static string ProfilePage_games_played_title {
            get {
                return ResourceManager.GetString("ProfilePage_games_played_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Games won.
        /// </summary>
        public static string ProfilePage_games_won_title {
            get {
                return ResourceManager.GetString("ProfilePage_games_won_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Highest score.
        /// </summary>
        public static string ProfilePage_highest_score_label {
            get {
                return ResourceManager.GetString("ProfilePage_highest_score_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Other modes statistics.
        /// </summary>
        public static string ProfilePage_other_modes_stats_label {
            get {
                return ResourceManager.GetString("ProfilePage_other_modes_stats_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Themes collected.
        /// </summary>
        public static string ProfilePage_themes_collected_label {
            get {
                return ResourceManager.GetString("ProfilePage_themes_collected_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Profile.
        /// </summary>
        public static string ProfilePage_title {
            get {
                return ResourceManager.GetString("ProfilePage_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Win rate.
        /// </summary>
        public static string ProfilePage_win_rate_title {
            get {
                return ResourceManager.GetString("ProfilePage_win_rate_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Buy.
        /// </summary>
        public static string PurchaseThemeOverlay_buy_btn_text {
            get {
                return ResourceManager.GetString("PurchaseThemeOverlay_buy_btn_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на for.
        /// </summary>
        public static string PurchaseThemeOverlay_for_label {
            get {
                return ResourceManager.GetString("PurchaseThemeOverlay_for_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Do you want to buy the following theme?.
        /// </summary>
        public static string PurchaseThemeOverlay_message {
            get {
                return ResourceManager.GetString("PurchaseThemeOverlay_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Purchase theme.
        /// </summary>
        public static string PurchaseThemeOverlay_title {
            get {
                return ResourceManager.GetString("PurchaseThemeOverlay_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Color BOOM.
        /// </summary>
        public static string RainbowTheme_desc {
            get {
                return ResourceManager.GetString("RainbowTheme_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rainbow.
        /// </summary>
        public static string RainbowTheme_title {
            get {
                return ResourceManager.GetString("RainbowTheme_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Same tiles, different rarity, go on.
        /// </summary>
        public static string RarityNumberlessTheme_desc {
            get {
                return ResourceManager.GetString("RarityNumberlessTheme_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rarity (Numberless).
        /// </summary>
        public static string RarityNumberlessTheme_title {
            get {
                return ResourceManager.GetString("RarityNumberlessTheme_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Deep colors, royal vibe.
        /// </summary>
        public static string RoyalBlueTheme_desc {
            get {
                return ResourceManager.GetString("RoyalBlueTheme_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Royal Blue.
        /// </summary>
        public static string RoyalBlueTheme_title {
            get {
                return ResourceManager.GetString("RoyalBlueTheme_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Red and gold. Royal experience.
        /// </summary>
        public static string RoyalRedTheme_desc {
            get {
                return ResourceManager.GetString("RoyalRedTheme_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Royal Red.
        /// </summary>
        public static string RoyalRedTheme_title {
            get {
                return ResourceManager.GetString("RoyalRedTheme_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The pink fallen leaves will tell the story.
        /// </summary>
        public static string SakuraTheme_desc {
            get {
                return ResourceManager.GetString("SakuraTheme_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sakura.
        /// </summary>
        public static string SakuraTheme_title {
            get {
                return ResourceManager.GetString("SakuraTheme_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Apply.
        /// </summary>
        public static string Settings_apply_btn {
            get {
                return ResourceManager.GetString("Settings_apply_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Menu.
        /// </summary>
        public static string Settings_back_to_menu_btn_text {
            get {
                return ResourceManager.GetString("Settings_back_to_menu_btn_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на How to.
        /// </summary>
        public static string Settings_how_to_btn_text {
            get {
                return ResourceManager.GetString("Settings_how_to_btn_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Language.
        /// </summary>
        public static string Settings_lang_pick_label {
            get {
                return ResourceManager.GetString("Settings_lang_pick_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Nickname.
        /// </summary>
        public static string Settings_nickname_label {
            get {
                return ResourceManager.GetString("Settings_nickname_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter the name....
        /// </summary>
        public static string Settings_nickname_placeholder_text {
            get {
                return ResourceManager.GetString("Settings_nickname_placeholder_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Restart.
        /// </summary>
        public static string Settings_restart_btn_text {
            get {
                return ResourceManager.GetString("Settings_restart_btn_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Choose the theme style.
        /// </summary>
        public static string Settings_theme_pick_desc_label {
            get {
                return ResourceManager.GetString("Settings_theme_pick_desc_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Customization.
        /// </summary>
        public static string Settings_theme_pick_label {
            get {
                return ResourceManager.GetString("Settings_theme_pick_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Themes.
        /// </summary>
        public static string Settings_theme_pick_sub_label {
            get {
                return ResourceManager.GetString("Settings_theme_pick_sub_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Themes.
        /// </summary>
        public static string Settings_themes_btn_text {
            get {
                return ResourceManager.GetString("Settings_themes_btn_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings.
        /// </summary>
        public static string Settings_title {
            get {
                return ResourceManager.GetString("Settings_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Warm colors and comfort.
        /// </summary>
        public static string SolarTheme_desc {
            get {
                return ResourceManager.GetString("SolarTheme_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Solar.
        /// </summary>
        public static string SolarTheme_title {
            get {
                return ResourceManager.GetString("SolarTheme_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bip-bap-boop... Access granted.
        /// </summary>
        public static string TerminalRetroTheme_desc {
            get {
                return ResourceManager.GetString("TerminalRetroTheme_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Terminal.
        /// </summary>
        public static string TerminalRetroTheme_title {
            get {
                return ResourceManager.GetString("TerminalRetroTheme_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Try yourself in this color-associative theme.
        /// </summary>
        public static string TetrisNumberlessTheme_desc {
            get {
                return ResourceManager.GetString("TetrisNumberlessTheme_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tetris (Numberless).
        /// </summary>
        public static string TetrisNumberlessTheme_title {
            get {
                return ResourceManager.GetString("TetrisNumberlessTheme_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The Great City for The Great People.
        /// </summary>
        public static string TheGreatCityTheme_desc {
            get {
                return ResourceManager.GetString("TheGreatCityTheme_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The Great City.
        /// </summary>
        public static string TheGreatCityTheme_title {
            get {
                return ResourceManager.GetString("TheGreatCityTheme_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Themes.
        /// </summary>
        public static string Themes_title {
            get {
                return ResourceManager.GetString("Themes_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на If you are 太陽, be my 日の出.
        /// </summary>
        public static string TokyoTheme_desc {
            get {
                return ResourceManager.GetString("TokyoTheme_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tokyo.
        /// </summary>
        public static string TokyoTheme_title {
            get {
                return ResourceManager.GetString("TokyoTheme_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You can&apos;t purchase this theme as you have insufficient coins amount.
        /// </summary>
        public static string UnsuccessfulPurchaseOverlay_desc {
            get {
                return ResourceManager.GetString("UnsuccessfulPurchaseOverlay_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed.
        /// </summary>
        public static string UnsuccessfulPurchaseOverlay_title {
            get {
                return ResourceManager.GetString("UnsuccessfulPurchaseOverlay_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Vaporwave party. Feel the vibe.
        /// </summary>
        public static string VaporWaveTheme_desc {
            get {
                return ResourceManager.GetString("VaporWaveTheme_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Vaporwave.
        /// </summary>
        public static string VaporWaveTheme_title {
            get {
                return ResourceManager.GetString("VaporWaveTheme_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Continue.
        /// </summary>
        public static string VictoryOverlay_continue_btn_text {
            get {
                return ResourceManager.GetString("VictoryOverlay_continue_btn_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Menu.
        /// </summary>
        public static string VictoryOverlay_menu_btn_text {
            get {
                return ResourceManager.GetString("VictoryOverlay_menu_btn_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Restart.
        /// </summary>
        public static string VictoryOverlay_restart_btn_text {
            get {
                return ResourceManager.GetString("VictoryOverlay_restart_btn_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на VICTORY.
        /// </summary>
        public static string VictoryOverlay_title {
            get {
                return ResourceManager.GetString("VictoryOverlay_title", resourceCulture);
            }
        }
    }
}
