//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Game2048.Maui.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Game2048.Maui.Resources.Localization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Played your first game in 2048.
        /// </summary>
        public static string Ach_FirstGame_desc {
            get {
                return ResourceManager.GetString("Ach_FirstGame_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на First steps.
        /// </summary>
        public static string Ach_FirstGame_title {
            get {
                return ResourceManager.GetString("Ach_FirstGame_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Used undo for the first time.
        /// </summary>
        public static string Ach_FirstUndo_desc {
            get {
                return ResourceManager.GetString("Ach_FirstUndo_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Back to the future!.
        /// </summary>
        public static string Ach_FirstUndo_title {
            get {
                return ResourceManager.GetString("Ach_FirstUndo_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Beaten 2048 without undo .
        /// </summary>
        public static string Ach_NoUndoVictory_desc {
            get {
                return ResourceManager.GetString("Ach_NoUndoVictory_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No mistakes!.
        /// </summary>
        public static string Ach_NoUndoVictory_title {
            get {
                return ResourceManager.GetString("Ach_NoUndoVictory_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Played 100 games.
        /// </summary>
        public static string Ach_Play100Games_desc {
            get {
                return ResourceManager.GetString("Ach_Play100Games_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Gamer.
        /// </summary>
        public static string Ach_Play100Games_title {
            get {
                return ResourceManager.GetString("Ach_Play100Games_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Played 10 games.
        /// </summary>
        public static string Ach_Play10Games_desc {
            get {
                return ResourceManager.GetString("Ach_Play10Games_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Keep trying.
        /// </summary>
        public static string Ach_Play10Games_title {
            get {
                return ResourceManager.GetString("Ach_Play10Games_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Merged a 1024 tile.
        /// </summary>
        public static string Ach_Reach1024_desc {
            get {
                return ResourceManager.GetString("Ach_Reach1024_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Almost there!.
        /// </summary>
        public static string Ach_Reach1024_title {
            get {
                return ResourceManager.GetString("Ach_Reach1024_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Merged a 128 tile.
        /// </summary>
        public static string Ach_Reach128_desc {
            get {
                return ResourceManager.GetString("Ach_Reach128_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Wasn&apos;t that hard, right?.
        /// </summary>
        public static string Ach_Reach128_title {
            get {
                return ResourceManager.GetString("Ach_Reach128_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Merged a 2048 tile.
        /// </summary>
        public static string Ach_Reach2048_desc {
            get {
                return ResourceManager.GetString("Ach_Reach2048_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на GOLD GOLD GOLD.
        /// </summary>
        public static string Ach_Reach2048_title {
            get {
                return ResourceManager.GetString("Ach_Reach2048_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Merged a 256 tile.
        /// </summary>
        public static string Ach_Reach256_desc {
            get {
                return ResourceManager.GetString("Ach_Reach256_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 2^8.
        /// </summary>
        public static string Ach_Reach256_title {
            get {
                return ResourceManager.GetString("Ach_Reach256_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Merged a 512 tile.
        /// </summary>
        public static string Ach_Reach512_desc {
            get {
                return ResourceManager.GetString("Ach_Reach512_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Two more to go!.
        /// </summary>
        public static string Ach_Reach512_title {
            get {
                return ResourceManager.GetString("Ach_Reach512_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Merged a 64 tile.
        /// </summary>
        public static string Ach_Reach64_desc {
            get {
                return ResourceManager.GetString("Ach_Reach64_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на That&apos;s going somewhere!.
        /// </summary>
        public static string Ach_Reach64_title {
            get {
                return ResourceManager.GetString("Ach_Reach64_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Score 1000 points in one game.
        /// </summary>
        public static string Ach_Score1000_desc {
            get {
                return ResourceManager.GetString("Ach_Score1000_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Scorer.
        /// </summary>
        public static string Ach_Score1000_title {
            get {
                return ResourceManager.GetString("Ach_Score1000_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Score 5000 points in one game.
        /// </summary>
        public static string Ach_Score5000_desc {
            get {
                return ResourceManager.GetString("Ach_Score5000_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Big numbers.
        /// </summary>
        public static string Ach_Score5000_title {
            get {
                return ResourceManager.GetString("Ach_Score5000_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Progress.
        /// </summary>
        public static string Achievements_progress_label {
            get {
                return ResourceManager.GetString("Achievements_progress_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Achievements.
        /// </summary>
        public static string Achievements_title {
            get {
                return ResourceManager.GetString("Achievements_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings.
        /// </summary>
        public static string Game_settings_btn_text {
            get {
                return ResourceManager.GetString("Game_settings_btn_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 2048.
        /// </summary>
        public static string Game_title {
            get {
                return ResourceManager.GetString("Game_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Undo.
        /// </summary>
        public static string Game_undo_btn_text {
            get {
                return ResourceManager.GetString("Game_undo_btn_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MODE SELECTION.
        /// </summary>
        public static string GameModes_title {
            get {
                return ResourceManager.GetString("GameModes_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Menu.
        /// </summary>
        public static string GameOverOverlay_menu_btn_text {
            get {
                return ResourceManager.GetString("GameOverOverlay_menu_btn_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Try again.
        /// </summary>
        public static string GameOverOverlay_restart_btn_text {
            get {
                return ResourceManager.GetString("GameOverOverlay_restart_btn_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на GAME OVER.
        /// </summary>
        public static string GameOverOverlay_title {
            get {
                return ResourceManager.GetString("GameOverOverlay_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Undo 5 moves.
        /// </summary>
        public static string GameOverOverlay_undo5_btn_text {
            get {
                return ResourceManager.GetString("GameOverOverlay_undo5_btn_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на GAME MODES.
        /// </summary>
        public static string Menu_game_modes_btn_text {
            get {
                return ResourceManager.GetString("Menu_game_modes_btn_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на HOW TO.
        /// </summary>
        public static string Menu_how_to_btn_text {
            get {
                return ResourceManager.GetString("Menu_how_to_btn_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SETTINGS.
        /// </summary>
        public static string Menu_settings_btn_text {
            get {
                return ResourceManager.GetString("Menu_settings_btn_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ver. 1.0.
        /// </summary>
        public static string Menu_version_text {
            get {
                return ResourceManager.GetString("Menu_version_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на How to.
        /// </summary>
        public static string Settings_how_to_btn_text {
            get {
                return ResourceManager.GetString("Settings_how_to_btn_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Restart.
        /// </summary>
        public static string Settings_restart_btn_text {
            get {
                return ResourceManager.GetString("Settings_restart_btn_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Themes.
        /// </summary>
        public static string Settings_themes_btn_text {
            get {
                return ResourceManager.GetString("Settings_themes_btn_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings.
        /// </summary>
        public static string Settings_title {
            get {
                return ResourceManager.GetString("Settings_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Continue.
        /// </summary>
        public static string VictoryOverlay_continue_btn_text {
            get {
                return ResourceManager.GetString("VictoryOverlay_continue_btn_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Menu.
        /// </summary>
        public static string VictoryOverlay_menu_btn_text {
            get {
                return ResourceManager.GetString("VictoryOverlay_menu_btn_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Restart.
        /// </summary>
        public static string VictoryOverlay_restart_btn_text {
            get {
                return ResourceManager.GetString("VictoryOverlay_restart_btn_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на VICTORY.
        /// </summary>
        public static string VictoryOverlay_title {
            get {
                return ResourceManager.GetString("VictoryOverlay_title", resourceCulture);
            }
        }
    }
}
